### ISSUE TITLE
There is some issues this repository

### ISSUE THREAD

**Issue by godhj93** [kimgs20/cpp_basic#1]
![Screenshot from 2022-02-28 13-20-36](https://user-images.githubusercontent.com/70679753/155923486-2e2af0b3-782c-4979-91d0-d3e524dfff4c.png)

**Comment by seunghwan6960** [comment]
![image](https://user-images.githubusercontent.com/73050200/155923882-e2085110-925d-4a86-a5f6-3eff210b5c7a.png)

**Comment by seunghwan6960** [comment]
![image](https://user-images.githubusercontent.com/73050200/155923947-87a80442-0060-4315-b287-170f186597e5.png)
